### ISSUE TITLE
Error reported when using AG mode to prove IMO problem

### ISSUE THREAD

**Issue by TriedTired99** [google-deepmind/alphageometry#107]
When I use the AG mode to prove the IMO problem, I encounter **numericals.InvalidLineIntersectError**. 
This issue occurs in imo_2012_p5 and imo_2018_p1. Has anyone encountered the same problem?

**Comment by TriedTired99** [comment]
Traceback (most recent call last):
  File "/home/leo/miniconda3/envs/ag/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/leo/miniconda3/envs/ag/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/leo/alphageometry-main/alphageometry.py", line 651, in <module>
    app.run(main)
  File "/home/leo/miniconda3/envs/ag/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/leo/miniconda3/envs/ag/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/leo/alphageometry-main/alphageometry.py", line 638, in main
    run_alphageometry(
  File "/home/leo/alphageometry-main/alphageometry.py", line 580, in run_alphageometry
    if run_ddar(g_new, p_new, out_file):
  File "/home/leo/alphageometry-main/alphageometry.py", line 217, in run_ddar
    ddar.solve(g, RULES, p, max_level=1000)
  File "/home/leo/alphageometry-main/ddar.py", line 95, in solve
    dervs, eq4, next_branches, added = saturate_or_goal(
  File "/home/leo/alphageometry-main/ddar.py", line 50, in saturate_or_goal
    added, derv, eq4, n_branching = dd.bfs_one_level(
  File "/home/leo/alphageometry-main/dd.py", line 1094, in bfs_one_level
    add = g.add_piece(name, args, deps=deps)
  File "/home/leo/alphageometry-main/graph.py", line 697, in add_piece
    return self.add_cyclic(args, deps)
  File "/home/leo/alphageometry-main/graph.py", line 1510, in add_cyclic
    all_circles.append(self.get_circle_thru_triplet(p1, p2, p3))
  File "/home/leo/alphageometry-main/graph.py", line 859, in get_circle_thru_triplet
    return self.get_new_circle_thru_triplet(p1, p2, p3)
  File "/home/leo/alphageometry-main/graph.py", line 868, in get_new_circle_thru_triplet
    circle.num = nm.Circle(p1=p1.num, p2=p2.num, p3=p3.num)
  File "/home/leo/alphageometry-main/numericals.py", line 407, in __init__
    center = line_line_intersection(l12, l23)
  File "/home/leo/alphageometry-main/numericals.py", line 584, in line_line_intersection
    raise InvalidLineIntersectError
numericals.InvalidLineIntersectError
