### ISSUE TITLE
Tests not passed

### ISSUE THREAD

**Issue by Jerry-Master** [google-deepmind/alphageometry#14]
I followed your instructions and got one test not passed. It says the following:

```
FAIL: test_lm_score_may_fail_numerically_for_external_meliad (__main__.LmInferenceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/array50tb/projects/alphageometry/lm_inference_test.py", line 82, in test_lm_score_may_fail_numerically_for_external_meliad
    self.assertEqual(
AssertionError: Lists differ: [-1.1633697, -1.122621] != [-1.1860729455947876, -1.1022869348526]

First differing element 0:
-1.1633697
-1.1860729455947876

- [-1.1633697, -1.122621]
+ [-1.1860729455947876, -1.1022869348526]

----------------------------------------------------------------------
Ran 2 tests in 82.530s

FAILED (failures=1)
****
```

What could be causing it?

**Comment by jiakai0419** [comment]
I also encountered the same problem

**Comment by Faultiness** [comment]
Same error
```
FAIL: test_lm_score_may_fail_numerically_for_external_meliad (__main__.LmInferenceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/data/username/imo/alphageometry/lm_inference_test.py", line 82, in test_lm_score_may_fail_numerically_for_external_meliad
    self.assertEqual(
AssertionError: Lists differ: [-1.1633697, -1.122621] != [-1.1860729455947876, -1.1022869348526]

First differing element 0:
-1.1633697
-1.1860729455947876

- [-1.1633697, -1.122621]
+ [-1.1860729455947876, -1.1022869348526]

----------------------------------------------------------------------
Ran 2 tests in 126.464s

FAILED (failures=1)

```

**Comment by thtrieu** [comment]
It seems the meliad library is not numerically stable, giving different scores for different users.
I will put a note in the README (https://github.com/google-deepmind/alphageometry/commit/a8a1dc70818c1253b6524d761510a6ec6df39c07)
For now, it seems the small difference in score does not affect `run.sh` and all other tests in `run_tests.sh`,
I will let this test fail while we learn more about meliad implementation and outputs.

**Comment by jackliugithub** [comment]
same here:

FAIL: test_lm_score_may_fail_numerically_for_external_meliad (__main__.LmInferenceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Documents/alphageometry-main/lm_inference_test.py", line 82, in test_lm_score_may_fail_numerically_for_external_meliad
    self.assertEqual(
AssertionError: Lists differ: [-1.1898218, -1.1082345] != [-1.1860729455947876, -1.1022869348526]
 
First differing element 0:
-1.1898218
-1.1860729455947876
 
- [-1.1898218, -1.1082345]
+ [-1.1860729455947876, -1.1022869348526]
 
----------------------------------------------------------------------
Ran 2 tests in 82.937s

**Comment by yfcai1116** [comment]
same here
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/python_code/alphageometry-main/lm_inference_test.py", line 82, in test_lm_score_may_fail_numerically_for_external_meliad
    self.assertEqual(
AssertionError: Lists differ: [-1.1563942, -1.1297226] != [-1.1860729455947876, -1.1022869348526]

First differing element 0:
-1.1563942
-1.1860729455947876

- [-1.1563942, -1.1297226]
+ [-1.1860729455947876, -1.1022869348526]

----------------------------------------------------------------------
Ran 2 tests in 62.007s

FAILED (failures=1)

**Comment by soxziw** [comment]
> It seems the meliad library is not numerically stable, giving different scores for different users. I will put a note in the README ([a8a1dc7](https://github.com/google-deepmind/alphageometry/commit/a8a1dc70818c1253b6524d761510a6ec6df39c07)) For now, it seems the small difference in score does not affect `run.sh` and all other tests in `run_tests.sh`, I will let this test fail while we learn more about meliad implementation and outputs.

I have encountered the same error here. Indeed, it does not affect other tests in `run_tests.sh` and the orthocenter problem in `run.sh`. 

However, I find it is not successful when solving Olympiad geometry. For example, the program terminates early with `DD+AR failed to solve the problem.` without new LM output generated when solving 2019 p6. (No reason or error to trackback... So weird)

Could you provide the hardware you use to run all Olympiad geometry successfully for me to reproduce the results? (I use Ubuntu 20.04, Python 3.10.12, NVIDIA T4 16GB)

**Comment by robotzheng** [comment]
======================================================================
FAIL: test_lm_score_may_fail_numerically_for_external_meliad (__main__.LmInferenceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/notebook/code/personal/80306170/AGI/alphageometry/lm_inference_test.py", line 82, in test_lm_score_may_fail_numerically_for_external_meliad
    self.assertEqual(
AssertionError: Lists differ: [-1.1633697, -1.122621] != [-1.1860729455947876, -1.1022869348526]

First differing element 0:
-1.1633697
-1.1860729455947876

- [-1.1633697, -1.122621]
+ [-1.1860729455947876, -1.1022869348526]

----------------------------------------------------------------------
Ran 2 tests in 82.584s

FAILED (failures=1)

**Comment by aemartinez** [comment]
Same here, the only test that does not pass when executing `bash run_tests.sh` is `test_lm_score_may_fail_numerically_for_external_meliad`.

My specific numbers:

```
AssertionError: Lists differ: [-1.1831452, -1.112445] != [-1.1860729455947876, -1.1022869348526]

First differing element 0:
-1.1831452
-1.1860729455947876

- [-1.1831452, -1.112445]
+ [-1.1860729455947876, -1.1022869348526]
```

My setup: Apple M1, macOS Ventura 13.6.1, Python 3.10.8, tensorflow 2.13.0

**Comment by soxziw** [comment]
> > It seems the meliad library is not numerically stable, giving different scores for different users. I will put a note in the README ([a8a1dc7](https://github.com/google-deepmind/alphageometry/commit/a8a1dc70818c1253b6524d761510a6ec6df39c07)) For now, it seems the small difference in score does not affect `run.sh` and all other tests in `run_tests.sh`, I will let this test fail while we learn more about meliad implementation and outputs.
> 
> @thtrieu I have encountered the same error here. Indeed, it does not affect other tests in `run_tests.sh` and the orthocenter problem in `run.sh`.
> 
> However, I find it is not successful when solving Olympiad geometry. For example, when solving 2019 p6, the program terminates early with `DD+AR failed to solve the problem.` without new LM output generated. (No reason or error to trackback... So weird) (full output log: https://drive.google.com/file/d/1btni6zroBbDLz6OBMpifTyj74bjL5fFy/view?usp=drive_link)
> 
> Could you please tell the specific hardware you use to run all Olympiad geometry successfully? (I use Ubuntu 20.04, Python 3.10.12, 64-core vCPU, 2*NVIDIA A10(24GB) but fail to reproduce the results)

Problems solved using Colab!

**Comment by faraday** [comment]
@soxziw I'm running this in Google Colab and I got the exact same failure when running run_tests.sh

```
FAIL: test_lm_score_may_fail_numerically_for_external_meliad (__main__.LmInferenceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/content/alphageometry/lm_inference_test.py", line 82, in test_lm_score_may_fail_numerically_for_external_meliad
    self.assertEqual(
AssertionError: Lists differ: [-1.1527003, -1.1230755] != [-1.1860729455947876, -1.1022869348526]

First differing element 0:
-1.1527003
-1.1860729455947876

- [-1.1527003, -1.1230755]
+ [-1.1860729455947876, -1.1022869348526]
```

What kind of GPU did you get when your tests were passing?

**Comment by soxziw** [comment]
> @soxziw I'm running this in Google Colab and I got the exact same failure when running run_tests.sh
> 
> ```
> FAIL: test_lm_score_may_fail_numerically_for_external_meliad (__main__.LmInferenceTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/content/alphageometry/lm_inference_test.py", line 82, in test_lm_score_may_fail_numerically_for_external_meliad
>     self.assertEqual(
> AssertionError: Lists differ: [-1.1527003, -1.1230755] != [-1.1860729455947876, -1.1022869348526]
> 
> First differing element 0:
> -1.1527003
> -1.1860729455947876
> 
> - [-1.1527003, -1.1230755]
> + [-1.1860729455947876, -1.1022869348526]
> ```
> 
> What kind of instance or GPU did you get when your tests were passing?

The free TPU

**Comment by TriedTired99** [comment]
> > @soxziw I'm running this in Google Colab and I got the exact same failure when running run_tests.sh
> > ```
> > FAIL: test_lm_score_may_fail_numerically_for_external_meliad (__main__.LmInferenceTest)
> > ----------------------------------------------------------------------
> > Traceback (most recent call last):
> >   File "/content/alphageometry/lm_inference_test.py", line 82, in test_lm_score_may_fail_numerically_for_external_meliad
> >     self.assertEqual(
> > AssertionError: Lists differ: [-1.1527003, -1.1230755] != [-1.1860729455947876, -1.1022869348526]
> > 
> > First differing element 0:
> > -1.1527003
> > -1.1860729455947876
> > 
> > - [-1.1527003, -1.1230755]
> > + [-1.1860729455947876, -1.1022869348526]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What kind of instance or GPU did you get when your tests were passing?
> 
> The free TPU
Hello, have you changed to a different version of jax? I am unable to call TPU using the dependency library in requirement.txt. I don't know if this is due to Meliad's influence, which prevented me from using GPU or CPU to reproduce the results in the paper.

**Comment by TriedTired99** [comment]
> > @soxziw I'm running this in Google Colab and I got the exact same failure when running run_tests.sh
> > ```
> > FAIL: test_lm_score_may_fail_numerically_for_external_meliad (__main__.LmInferenceTest)
> > ----------------------------------------------------------------------
> > Traceback (most recent call last):
> >   File "/content/alphageometry/lm_inference_test.py", line 82, in test_lm_score_may_fail_numerically_for_external_meliad
> >     self.assertEqual(
> > AssertionError: Lists differ: [-1.1527003, -1.1230755] != [-1.1860729455947876, -1.1022869348526]
> > 
> > First differing element 0:
> > -1.1527003
> > -1.1860729455947876
> > 
> > - [-1.1527003, -1.1230755]
> > + [-1.1860729455947876, -1.1022869348526]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What kind of instance or GPU did you get when your tests were passing?
> 
> The free TPU

Hello, have you changed to a different version of jax? I am unable to call TPU using the dependency library in requirement.txt. I don't know if this is due to Meliad's influence, which prevented me from using GPU or CPU to reproduce the results in the paper.

**Comment by TriedTired99** [comment]
> > @soxziw I'm running this in Google Colab and I got the exact same failure when running run_tests.sh
> > ```
> > FAIL: test_lm_score_may_fail_numerically_for_external_meliad (__main__.LmInferenceTest)
> > ----------------------------------------------------------------------
> > Traceback (most recent call last):
> >   File "/content/alphageometry/lm_inference_test.py", line 82, in test_lm_score_may_fail_numerically_for_external_meliad
> >     self.assertEqual(
> > AssertionError: Lists differ: [-1.1527003, -1.1230755] != [-1.1860729455947876, -1.1022869348526]
> > 
> > First differing element 0:
> > -1.1527003
> > -1.1860729455947876
> > 
> > - [-1.1527003, -1.1230755]
> > + [-1.1860729455947876, -1.1022869348526]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What kind of instance or GPU did you get when your tests were passing?
> 
> The free TPU

Hello, have you changed to a different version of jax? I am unable to call TPU using the dependency library in requirements.txt. I don't know if this is due to Meliad's influence, which prevented me from using GPU or CPU to reproduce the results in the paper.

**Comment by wangguan1995** [comment]
OHHHHH, Here we met:

https://github.com/google-deepmind/alphageometry/issues/143
