### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python'

### ISSUE THREAD

**Issue by vnpower** [google-deepmind/alphageometry#45]
I had tried to run the command in Ubuntu with python3.10:
```
python -m alphageometry \
--alsologtostderr \
--problems_file=$(pwd)/examples.txt \
--problem_name=orthocenter \
--mode=alphageometry \
"${DDAR_ARGS[@]}" \
"${SEARCH_ARGS[@]}" \
"${LM_ARGS[@]}"
```

then I got the below issue:

> /home/vikisu/alphageometry/lib/python3.10/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
>   jax.tree_util.register_keypaths(data_clz, keypaths)
> /home/vikisu/alphageometry/lib/python3.10/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
>   jax.tree_util.register_keypaths(data_clz, keypaths)
> /home/vikisu/alphageometry/lib/python3.10/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
>   jax.tree_util.register_keypaths(data_clz, keypaths)
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/vikisu/alphageometry/alphageometry.py", line 28, in <module>
>     import lm_inference as lm
>   File "/home/vikisu/alphageometry/lm_inference.py", line 20, in <module>
>     import models  # pylint: disable=unused-import
>   File "/home/vikisu/alphageometry/models.py", line 24, in <module>
>     from transformer import models
>   File "/home/vikisu/alphageometry/meliad_lib/meliad/transformer/models.py", line 25, in <module>
>     import  metrics_summary
>   File "/home/vikisu/alphageometry/meliad_lib/meliad/metrics_summary.py", line 20, in <module>
>     from clu import metric_writers
>   File "/home/vikisu/alphageometry/lib/python3.10/site-packages/clu/metric_writers/__init__.py", line 52, in <module>
>     from clu.metric_writers.summary_writer import SummaryWriter
>   File "/home/vikisu/alphageometry/lib/python3.10/site-packages/clu/metric_writers/summary_writer.py", line 27, in <module>
>     import tensorflow as tf
>   File "/home/vikisu/alphageometry/lib/python3.10/site-packages/tensorflow/__init__.py", line 38, in <module>
>     from tensorflow.python.tools import module_util as _module_util
> ModuleNotFoundError: No module named 'tensorflow.python'

**Comment by Kev1nSha0** [comment]
I met the same problem, and I think I solved it just by uninstalling the TensorFlow and pip install it back, and it's working
