### ISSUE TITLE
Cannot run on Colab

### ISSUE THREAD

**Issue by TueNguyen2006** [google-deepmind/alphageometry#48]
I ran this Colab file "https://colab.research.google.com/drive/1vyqbBzBDpgNhjGGuGsiVJb336-WDunOv?usp=sharing", and I performed the environment setup and setup process smoothly. However, when it came to the inference step, it encountered this error.

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/alphageometry/alphageometry.py", line 26, in <module>
    import ddar
  File "/content/alphageometry/ddar.py", line 20, in <module>
    import dd
  File "/content/alphageometry/dd.py", line 24, in <module>
    import graph as gh
  File "/content/alphageometry/graph.py", line 31, in <module>
    import numericals as nm
  File "/content/alphageometry/numericals.py", line 30, in <module>
    matplotlib.use('TkAgg')
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/cbook/deprecation.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/__init__.py", line 1281, in use
    plt.switch_backend(name)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/pyplot.py", line 234, in switch_backend
    raise ImportError(
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

**Comment by yuta0x89** [comment]
By replacing line 30 of ‘numerical.py’ from ‘matplotlib.use(‘TkAgg’)’ to ‘matplotlib.use(‘Agg’)’, this error will be resolved.

**Comment by tpgh24** [comment]
I created a fork of AlphaGeometry and made various improvements, including a Kaggle notebook. It should run on Colab too with some minor modifications, but the free version of Kaggle reliably provides 2 T4 GPUs, while in the free version of Colab, one can almost never get GPUs. Check it out at https://github.com/tpgh24/ag4masses.
