### ISSUE TITLE
error solving 

### ISSUE THREAD

**Issue by unhandyandy** [google-deepmind/alphageometry#71]
When running AG on imo_2005_p5, got this error.   

TypeError: cannot unpack non-iterable Point object:

```
Traceback (most recent call last):
  File "/N/soft/sles15/python/gnu/3.10.5/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/N/soft/sles15/python/gnu/3.10.5/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/geode2/home/u020/dabrowsa/BigRed200/alphageometry/alphageometry.py", line 651, in <module>
    app.run(main)
  File "/geode2/home/u020/dabrowsa/BigRed200/alphageometry/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/geode2/home/u020/dabrowsa/BigRed200/alphageometry/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/geode2/home/u020/dabrowsa/BigRed200/alphageometry/alphageometry.py", line 638, in main
    run_alphageometry(
  File "/geode2/home/u020/dabrowsa/BigRed200/alphageometry/alphageometry.py", line 521, in run_alphageometry
    g, _ = gh.Graph.build_problem(p, DEFINITIONS)
  File "/geode2/home/u020/dabrowsa/BigRed200/alphageometry/graph.py", line 523, in build_problem
    check = nm.check(pr.goal.name, args)
  File "/geode2/home/u020/dabrowsa/BigRed200/alphageometry/numericals.py", line 649, in check
    return fun(args)
  File "/geode2/home/u020/dabrowsa/BigRed200/alphageometry/numericals.py", line 705, in check_cyclic
    (a, b, c), *ps = points
TypeError: cannot unpack non-iterable Point object
```

**Comment by Ehisnet** [comment]
I will try and run this problem and see what happens

**Comment by DataStunner** [comment]
It's happening for all the problems which involves proving cyclic points (i.e. ? cyclic a b c d). Any work around for this?

**Comment by unhandyandy** [comment]
@DataStunner 
That's an interesting lead, thanks.

**Comment by unhandyandy** [comment]
OK, it seems there's a mistake in line 705 of alphageometry.py.  Try changing 
  `(a, b, c), *ps = points`
to 
  `a, b, c, *ps = points`
That seems to work for me.

**Comment by DataStunner** [comment]
@unhandyandy Its working now. Thanks!

**Comment by unhandyandy** [comment]
I'm leaving this open till the devs fix it in the repo.

**Comment by ppaaron** [comment]
@unhandyandy I found the "mistake" in the numericals.py file, not alphageometry.py, and its working for me now.

> OK, it seems there's a mistake in line 705 of alphageometry.py. Try changing `(a, b, c), *ps = points` to `a, b, c, *ps = points` That seems to work for me.

**Comment by tpgh24** [comment]
I made some improvements in a fork repository and have some ideas to further improve the performance of AG, check out 
[AG4Masses](https://github.com/tpgh24/ag4masses) and [issue 110](https://github.com/google-deepmind/alphageometry/issues/110). In it this and several other bugs are fixed.
